print("LINKEDIN LOGIN SETUP INSTRUCTIONS")
print("=" * 40)

print("\n1. CLOSE ALL BROWSER WINDOWS on your computer")
print("2. OPEN your regular web browser (Chrome, Edge, Firefox, etc.)")
print("3. GO TO: https://www.linkedin.com/login")
print("4. LOG IN to your LinkedIn account with your email and password")
print("5. COMPLETE THE LOGIN PROCESS (including any 2-factor authentication)")
print("6. LEAVE THE BROWSER OPEN and LOGGED INTO LINKEDIN")
print("7. RETURN TO THIS COMMAND PROMPT")
print("\nAfter completing the above steps, run this command in a new command prompt:")
print("pm2 start linkedin_watcher.py")
print("\nThe watcher will use your existing LinkedIn session from the browser you left open.")
print("\nWhen you want to stop the watcher later, run: pm2 stop linkedin_watcher")